### ISSUE TITLE
[Migrate]: Activity Embeds

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#116]
### Link to the existing BP Codex page.

https://codex.buddypress.org/activity-embeds/

### What needs to be done?

All WP Codex links should be replace by their equivalent in WordPress documentation.
The introductive text needs to be updated.
Instead of an Embedded Activity, we should use a screenshot.

### Handbook to migrate the page in

buddypress/docs/developer

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Migrate issue/task created".
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by vapvarun** [comment]
Preview: https://github.com/vapvarun/BuddyPress/blob/activity-embeds/docs/developer/activity-embeds.md

**Comment by renatonascalves** [comment]
TIL: https://github.com/vapvarun/BuddyPress/blob/activity-embeds/docs/developer/activity-embeds.md#rest-api-endpoints-for-embeds

We should find a page in the REST API documentation for this too. Since it is a custom but not a core endpoint.
