### ISSUE TITLE
[Migrate]: Customizing Labels, Messages, and URLs

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#135]
### Link to the existing BP Codex page.

https://codex.buddypress.org/getting-started/customizing/customizing-labels-messages-and-urls/

### What needs to be done?

The only thing that needs to be migrated is what is written about how to use a custom language file. It should also be tested to check it’s still behaving as expected as I think i18n changes introduced in WP 4.6 were preventing these custom language files to be used.
Explanations about deprecated slug constants need to be skipped.

NB: this should be in an Advanced user chapter.  

### Handbook to migrate the page in

buddypress/docs/user

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Migrate issue/task created".
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by vapvarun** [comment]
Preview: https://github.com/vapvarun/BuddyPress/blob/customizing-labels-messages-and-urls/docs/user/administration/users/customizing-labels-messages-and-urls.md
