### ISSUE TITLE
[Migrate]: Member Types

### ISSUE THREAD

**Issue by vapvarun** [buddypress/bp-documentation#152]
### Link to the existing BP Codex page.

https://codex.buddypress.org/?p=14566

### What needs to be done?

Link to the existing BP Codex page.
https://codex.buddypress.org/developer/member-types/

What needs to be done?
- **Introduction to BuddyPress Member Types**: Categorizing community members into roles like "Students," "Teachers," "Alumni."
- **Enhanced User Experience**: Member Types enable tailored interactions and access controls to enhance the community environment.
- **Creating Member Types**: The process involves defining unique identifiers and labels within the BuddyPress theme or a custom plugin.
- **Assigning Member Types**: Administrators can assign types to users manually or programmatically, individually, and in bulk.
- **Utilizing Member Types**: Leverage types for creating specific directories, customizing profile fields, and setting access controls.
- **Custom Functions**: Provided for adding, updating, and removing Member Types, querying members by type, and fetching a user's Member Type.
- **Best Practices**: Managing Member Types effectively requires uniqueness, descriptiveness, community engagement, and clear documentation.

NB: this should be in an Advanced user chapter.

Handbook path
buddypress/docs/user/administration/users)/member-types.md

### Handbook to migrate the page in

buddypress/docs/user

### Tasks to accomplish

- [X] This task has been added to the "Todo" panel of the Documentation project.
- [X] The corresponding line of the `data/README.md` Pages list has been marked as "Migrate issue/task created".
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by vapvarun** [comment]
Prepare the patch here: https://github.com/vapvarun/BuddyPress/tree/member-types-patch-1
Preview: https://github.com/vapvarun/BuddyPress/blob/member-types-patch-1/docs/user/administration/users/member-types.md

**Comment by imath** [comment]
Thanks a lot for your terrific work on this 😍.

I just gave it a quick look and found possible improvements : since 7.0.0 it's no more needed to register a member type from code (plugin or theme).

Maybe the documentation should be split in 2 parts one for users: managing member types from administration and another one for developers: extending member types
Let's discuss about it Wednesday 😘
