### ISSUE TITLE
[Ignore]:  Using the Built-in WordPress Menus [Page ID 2622]

### ISSUE THREAD

**Issue by emaralive** [buddypress/bp-documentation#155]
### Link to the existing BP Codex page.

https://codex.buddypress.org/?p=2622

### Why should we ignore this page?

Because BuddyPress is not using this anymore! And, part of an archived section. Additionally has been replaced by:

> **[Navigation menus](https://github.com/buddypress/buddypress/tree/master/docs/user/administration/navigations)**

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Ignore issue/task created".
- [x] One of the BuddyPress Core committer reviewed it and agreed to ignore this Codex page.
- [x] The task was moved to the "Done" panel of the Documentation project.

**Comment by imath** [comment]
I agree, it should be ignored, thanks for your contribution 👍
