### ISSUE TITLE
[Ignore]:  Skeleton Component [Page ID 4642]

### ISSUE THREAD

**Issue by emaralive** [buddypress/bp-documentation#156]
### Link to the existing BP Codex page.

https://codex.buddypress.org/?p=4642

### Why should we ignore this page?

Because BuddyPress is not using this anymore! Additionally has been replaced by:

> **[Building a custom BuddyPress component](https://github.com/buddypress/buddypress/blob/master/docs/developer/component/build-component.md)**
> **[Why we make BuddyPress Add-ons?](https://github.com/buddypress/buddypress/blob/master/docs/developer/introduction/README.md#why-we-make-buddypress-add-ons)**
> **[WordPress Plugin development handbook](https://developer.wordpress.org/plugins/)**

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Ignore issue/task created".
- [x] One of the BuddyPress Core committer reviewed it and agreed to ignore this Codex page.
- [x] The task was moved to the "Done" panel of the Documentation project.

**Comment by imath** [comment]
I agree, it should be ignored, thanks for your contribution 👍
