### ISSUE TITLE
[Ignore]:  Developer and Designer Information BP 1.7

### ISSUE THREAD

**Issue by emaralive** [buddypress/bp-documentation#18]
### Link to the existing BP Codex page.

https://codex.buddypress.org/?p=5425

### Why should we ignore this page?

Because BuddyPress is not using this anymore! And, the page indicates the following:

> Archived file. Good only for BP 1.7 version

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Ignore issue/task created".
- [x] One of the BuddyPress Core committer reviewed it and agreed to ignore this Codex page.
- [x] The task was moved to the "Done" panel of the Documentation project.

**Comment by imath** [comment]
I agree! This page can be ignored, thanks for your help 👍
