### ISSUE TITLE
[Migrate]: BuddyPress Database Diagram

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#272]
### Link to the existing BP Codex page.

https://codex.buddypress.org/developer/buddypress-database-diagram/

### What needs to be done?

This is an interesting tool but it needs a lot of changes before being migrated:

- update the BP db diagram
- update links to the WordPress ones (regular & multisite).

### Handbook to migrate the page in

buddypress/docs/contributor

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Migrate issue/task created".
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by vapvarun** [comment]
Preview: https://github.com/vapvarun/BuddyPress/blob/buddypress-database-diagram/docs/developer/buddypress-database-diagram.md
