### ISSUE TITLE
[Add]: Create a pre-release test checklist

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#288]
### What needs to be done?

List all the tasks to perform to check a version is safe to be released & deployed in WP Plugin Directory.
There should be at least 2 scenarios:
- Fresh install
- Upgrade from a previous version using the upload tool of WP Add New plugin screen

We should also have 1 checklist for a regular WordPress and another one for Multisite WordPress. Don’t hesitate to comment this issue to share what tests should be done. Eg: Activate Groups component, create a group, invite a user etc..

### Handbook to add the page in

buddypress/docs/contributor

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by renatonascalves** [comment]
- Activate/deactivate without issues
- Updating core settings works
- Welcome redirect works
- ... (more soon)

**Comment by emaralive** [comment]
Something else to consider are the various compatible WP version (branches), I remember my 1st Trac ticket which was for BP 12 beta3, [9003](https://buddypress.trac.wordpress.org/ticket/9003) whereby the issue was with WP branch 5.8 and it looks like WP branch 6.6 may have some unexpected changes, e.g., see Trac ticket [9182](https://buddypress.trac.wordpress.org/ticket/9182). And, of course, there are the PHP versions...

edit:
On occasion, I forget to test against both **template packs**, i.e., Legacy & Nouveau; additionally, classic theme and block theme.

**Comment by paulgibbs** [comment]
Historically we had https://codex.buddypress.org/prelaunch-checklist/ which was more of the process around _making_ a release, rather than testing it.

**Comment by imath** [comment]
Hi @paulgibbs 

Thanks for your comment, we already migrated this page here: https://github.com/buddypress/buddypress/blob/master/docs/contributor/project/release/build-checklist.md

After the 12.1 release results, we've identified this potential improvement: before releasing a major/minor make some tests to prevent errors when users are upgrading.

During our last documentation meeting, we've decided to start with testing BuddyPress on a regular WordPress & BuddyPress network activated on a multisite WordPress.

Here's my suggestion as a start:

1. WordPress (regular)
 - Fresh Install,
 - Upgrade from the previous version
 - Activate / Deactivate all components without issues
 - Test Member block to check the BP REST API via the Autocomplete field
 - Test all Members front-end screen with BP Nouveau & BP Legacy template packs
2. WordPress Multisite (network activated)
 - Fresh Install,
 - Upgrade from the previous version,
 - Activate / Deactivate all components without issues
 - Test Member block to check the BP REST API via the Autocomplete field
 - Test all Members front-end screen with BP Nouveau & BP Legacy template packs

I believe that's already a nice list 😅.

**Comment by renatonascalves** [comment]
Thank you! That helps! :)

Here's the ticket, if you wanna keep track of what I'm trying to do: https://buddypress.trac.wordpress.org/ticket/9201

**Comment by imath** [comment]
I've tested this checklist during 14.1.0 packaging including an extra test to make sure 12.0.0 deprecated functions are loaded (install/upgrade) Testing a WP Multisite fresh install is pretty long: you need to setup the network. So here's the checklist we should test as a start:

1. WP Regular
- Fresh Install,
- Activate / Deactivate all components without issues
- Test Member block to check the BP REST API via the Autocomplete field
- Test all Members front-end screen with BP Nouveau & BP Legacy template packs

2. WordPress Multisite (network activated)
- Upgrade from the previous version,
- Activate / Deactivate all components without issues
- Test Member block to check the BP REST API via the Autocomplete field
- Test all Members front-end screen with BP Nouveau & BP Legacy template packs
