### ISSUE TITLE
[Ignore]:  Configuring Components [Page ID 1855]

### ISSUE THREAD

**Issue by emaralive** [buddypress/bp-documentation#36]
### Link to the existing BP Codex page.

https://codex.buddypress.org/?p=1855

### Why should we ignore this page?

Because BuddyPress is not using this anymore! And, the page indicates the following:

> Archived file. Good up to BP 1.6.5

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Ignore issue/task created".
- [x] One of the BuddyPress Core committer reviewed it and agreed to ignore this Codex page.
- [x] The task was moved to the "Done" panel of the Documentation project.

**Comment by imath** [comment]
Thanks for your work on it. I confirm we need to ignore this page.
