### ISSUE TITLE
[Ignore]:  Installation Wizard [Page ID 4098]

### ISSUE THREAD

**Issue by emaralive** [buddypress/bp-documentation#40]
### Link to the existing BP Codex page.

https://codex.buddypress.org/?p=4098

### Why should we ignore this page?

Because BuddyPress is not using this anymore! And, the page indicates the following:

> Archived file. This information is for BuddyPress installations up to version 1.6.5 only. There is no installation wizard for BuddyPress version 1.7 and above

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Ignore issue/task created".
- [x] One of the BuddyPress Core committer reviewed it and agreed to ignore this Codex page.
- [x] The task was moved to the "Done" panel of the Documentation project.

**Comment by imath** [comment]
I confirm! Thanks for you work on this 😍
