### ISSUE TITLE
[Migrate]: Installation

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#45]
### Link to the existing BP Codex page.

https://codex.buddypress.org/getting-started/setting-up-a-new-installation/

### What needs to be done?

The content needs to be updated too: it's no more needed to "Make sure you have pretty permalinks enabled on your WordPress install", since 12.0.0 BuddyPress also supports plain permalinks

### Handbook to migrate the page in

buddypress/docs/user

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Migrate issue/task created".
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by vapvarun** [comment]
Preview: https://github.com/vapvarun/BuddyPress/blob/activate-buddypress-patch-1/docs/user/getting-started/activate-buddypress.md
Branch: https://github.com/vapvarun/BuddyPress/tree/activate-buddypress-patch-1

**Comment by imath** [comment]
Thanks a lot @vapvarun 

Since 12.0.0, we don't need to set [pretty links](https://github.com/vapvarun/BuddyPress/blob/activate-buddypress-patch-1/docs/user/getting-started/activate-buddypress.md#step-3-enable-pretty-permalinks) for BuddyPress. Thanks to the BP Rewrites API we are finally supporting plain links!

**Comment by vapvarun** [comment]
@imath updated the doc and removed the permalink step.
