### ISSUE TITLE
[Migrate]: PHP version support

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#46]
### Link to the existing BP Codex page.

https://codex.buddypress.org/getting-started/php-version-support/

### What needs to be done?

Content also needs to be updated & discussed. For instance we could ease our life following WordPress PHP requirements.

### Handbook to migrate the page in

buddypress/docs/user

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Migrate issue/task created".
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by vapvarun** [comment]
Preview: https://github.com/vapvarun/BuddyPress/blob/php-version-support/docs/user/getting-started/php-version-support.md
Branch: https://github.com/vapvarun/BuddyPress/tree/php-version-support
