### ISSUE TITLE
[Migrate]:  Official Logos and Typeface

### ISSUE THREAD

**Issue by emaralive** [buddypress/bp-documentation#5]
### Link to the existing BP Codex page.

https://codex.buddypress.org/?p=1249

### What needs to be done?

Not quite ready to be migrated!

-  Determine the number of logo display images needed (Based on a new layout scheme)
-  Determine whether the downloadable files can remain where they currently reside or do they need to be migrated, as well.
-  Since "**BuddyPress**" is a **word mark** owned by the **WordPress Foundation**, determine whether it is just sufficient to provide some text and link to the "**[WordPress trademark policy](https://wordpressfoundation.org/trademark-policy/)**"
----  
Based on comments:

- Logos page to be located in root of the **`docs`** folder, e.g.,**` buddypress/docs/`**
- Assets for logos will be located in **`buddypress/docs/assets`**
----  

### Handbook to migrate the page in

buddypress/docs/

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Migrate issue/task created".
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by imath** [comment]
I wonder if we should move this information into main BuddyPress.org site. Using official material can also interest developers & contributors (who are users first of course). For instance WP Logos are into main [WordPress.org](https://wordpress.org/about/logos/) site.

**Comment by emaralive** [comment]
Since it is information intended for public use/consumption, that makes sense. However, work on the BuddyPress.org site is above my pay grade so, someone else would have to take over that work and it appears the site, in general, has other outdated information (outside of the scope of the codex), that needs to be scrubbed. 

Other relevant info regarding the logo page is that there are a couple of broken image links for **Large Icons (.psd)** and **Menu Icons (.psd)** (a.k.a, BuddyPress Header Icons), of which can be found starting at the following point:

https://codex.buddypress.org/official-fonts-and-logos/#:~:text=Disc%20Logo%20(PNG)-,Large%20Icons%20(.psd),-Menu%20Icons%20(.psd

Apparently, the source for the 2 display images (**icons32.png** & **menu.png**, respectively) was **buddypress.svn.wordpress.org** with a path to **/trunk/src/bp-core/admin/images/**, of which the image folder is empty, thus the broken image links. Not sure why the 2 images would be hosted from there but, I did a hop & skip backtrace through the various branches and found the 2 images (along with 4 other images) at branch 2.3, see the following link:

[Branch 2.3 image source](https://buddypress.svn.wordpress.org/branches/2.3/src/bp-core/admin/images/)

Neither here nor there, the indicated images should be moved to a more secure location for hosting and a final decision as to where this page should reside.

**Comment by imath** [comment]
Thanks for looking into these missing images, About where to put this doc resource. I was wondering if adding it directly to `buddypress/docs` and some other files like a page to select which handbook to browse would be a better idea than BuddyPress.org.

**Comment by emaralive** [comment]
I was contemplating your thoughts about placing this file, along with other files, in the root of the **`docs`** folder, with my eyes closed. :sleeping:  Does that mean that an **`asset`** folder would reside there also? 

There needs to be a place where the 2 missing images are to reside; or, would someone with access capabilities place them with the other logo images on **BuddyPress.org** site within the **`media`** folder? I'm thinking that either they all reside in the BuddyPress.org **`media`** folder or they all reside in an **'asset'** folder within the root of the **`docs`** folder with the exception that the GH repo option requires a 2 step process to download, e.g., click on link then on rendered page, click on the download button, which is a variation for the way it currentyl works, e.g., click on image then on rendered image, right click > save image as (of which depends on the mime type that dictates the download process, e.g.,  png vs pdf vs psd vs zip; the following screenshot illustrates the final download process after clicking a download link with GH option, at least it is consistent, thoughts?

![screenshot-github com-2024 01 14-14_10_41](https://github.com/buddypress/bp-documentation/assets/50045193/6595430c-3322-4009-af04-09a912a0945a)

As to:
> **a page to select which handbook to browse...**

That is a good idea, would/could act as a **TOC** of sorts which would facilitate navigation through the handbooks and provide a place to link up the Logo page (navigation needs further discussion).

As an aside, I wonder if it would advantageous for you to enable the **Discussions** feature for **`bp-documentation`** with the thought conversations such as this could be compartmentalized whereby not getting lost as issues are closed: meaning those discussions can always provide links to issues (issues can also provide links to discussions) whether they are open or closed. In addition:

- Ideas can be proposed
- Questions and Answers
- Polls
- General discussion
- Show and tell

The above are default categories shown when the Discussions feature is enabled, categories can to removed or added, along with the editing of category names/titles. There is also the ability to group categories within sections. The only caveat, is that there appears to be a bug with assigning/changing the icons (emojis) for category & section names/titles: meaning its best just to stick with the initial icons that get assigned by default.

Last but not least (for now), there are other topics that require hashing out, such as (just to outline a few):

- Should there be naming conventions for md files, screenshots & possible downloadable assets?
- General discussions about how to do something related to documentation.
- How to track which screenshots belong to which md files, to facilitate updating screenshots in the event that updating is required.
- How to facilitate navigation within each handbook and between handbooks.

**Comment by imath** [comment]
Thanks for your thoughts and suggestions, here is our [discussions area](https://github.com/buddypress/bp-documentation/discussions) we'll see how it goes.

- `buddypress/docs/assets` is a Yes
- The missing images are deprecated imho, we are now using WordPress Dashicons

I agree we'll need to think about the main TOC etc.. I'll open a new issue about it.

**Comment by emaralive** [comment]
I updated the issue to reflect information regarding where this page and assets will reside. 

Regarding the images that may or may not be deprecated, is there a source for this information, such as a ticket, dev note or other historical information that indicates such?

As for **Discussions**, I must admit, it is probably mainly for me as an attempt to flush out information that I presently have little to none knowledge of; meaning, I need consultation from subject matter experts in order to figure out what should be accomplished regarding the various pages that need to, either, be migrated, added or ignored and the nuances that may be involved in accomplishing such tasks.

**Comment by imath** [comment]
> Regarding the images that may or may not be deprecated, is there a source for this information, such as a ticket, dev note or other historical information that indicates such?

Not really they were removed in this commit: https://buddypress.trac.wordpress.org/changeset/10238
