### ISSUE TITLE
[Update]: BuddyPress repair tool

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#57]
### Link to the existing GH Documentation page.

https://github.com/buddypress/buddypress/blob/master/docs/user/administration/tools/repair.md

### What needs to be updated?

This page was quickly created to inform about the new tool to reset slugs. It should be updated to explain all the available tools and when to use each of these.

### Handbook of the page to update

buddypress/docs/user

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by emaralive** [comment]
Ugh, not sure how to link PR [296](https://github.com/buddypress/buddypress/pull/296), the only options for **Development** were my respositories or this one (buddypress/bp-documentation), so I linked the branch on my forked BuddyPress repository that I used to generate the PR.

**Comment by imath** [comment]
You did great! Thanks a lot for your work 💪
